INSERT INTO Categories (CategoryName, Description) VALUES ('Fruits', 'Fresh and delicious fruits');
INSERT INTO Categories (CategoryName, Description) VALUES ('Vegetables', 'A variety of fresh vegetables');
INSERT INTO Categories (CategoryName, Description) VALUES ('Dairy', 'Milk, cheese, and other dairy products');
INSERT INTO Categories (CategoryName, Description) VALUES ('Bakery', 'Freshly baked goods');
INSERT INTO Categories (CategoryName, Description) VALUES ('Meat', 'Various types of meat');
INSERT INTO Categories (CategoryName, Description) VALUES ('Beverages', 'A range of beverages');
INSERT INTO Categories (CategoryName, Description) VALUES ('Snacks', 'Snacks and finger foods');
INSERT INTO Categories (CategoryName, Description) VALUES ('Canned Goods', 'Canned and preserved items');
INSERT INTO Categories (CategoryName, Description) VALUES ('Grains', 'Rice, pasta, and grains');
INSERT INTO Categories (CategoryName, Description) VALUES ('Cleaning Supplies', 'Household cleaning supplies');
INSERT INTO Categories (CategoryName, Description) VALUES ('Condiments', 'Sauces, spices, and seasonings');
INSERT INTO Categories (CategoryName, Description) VALUES ('Frozen Foods', 'Frozen meals and ingredients');
INSERT INTO Categories (CategoryName, Description) VALUES ('Personal Care', 'Personal care and hygiene products');
